### PR TITLE
bugfix: fix GLM-4.7 detector regex stack overflow.

### LINKED ISSUE #751: [Bug]: GLM-4.7 Detector 正则表达式导致栈溢出崩溃
### Your environment

A3

main

## 基本信息

| 项目 | 内容 |
|------|------|
| **严重程度** | P0 - 服务崩溃 |
| **影响范围** | 所有使用 GLM-4.7 模型进行 Function Calling 的请求 |
| **引入提交** | `0c082f385e9b08a9e475247e64448b07bc37de52` |
| **提交信息** | `feat: add GLM-4.7 detector implementation and update tool call parser.` |
| **提交作者** | dengyingxu (dengyingxu1@jd.com) |
| **提交时间** | 2025年12月21日 21:52:32 (UTC+8) |
| **问题文件** | `xllm/function_call/glm47_detector.cpp` |

---

### 现象

服务在处理 GLM-4.7 模型生成的工具调用时发生崩溃，进程收到 SIGSEGV（段错误）信号后终止。

### 崩溃信号

```
Signal: SIGSEGV (Segmentation fault)
```

### Core Dump 分析结果

- **崩溃函数**: `xllm::function_call::Glm47Detector::detect_and_parse()`
- **崩溃位置**: `glm47_detector.cpp:270`
- **栈帧数量**: 168,425 帧
- **根本原因**: `std::regex` 引擎的 DFS（深度优先搜索）递归导致栈溢出

---

### 问题代码

**位置**: `glm47_detector.cpp` 第 31-39 行

```cpp
// 构造函数中初始化的正则表达式
func_call_regex_ = std::regex("<tool_call>[\\s\\S]*?</tool_call>",
                              std::regex_constants::ECMAScript);
func_detail_regex_ =
    std::regex("<tool_call>([\\s\\S]*?)(<arg_key>[\\s\\S]*?)?</tool_call>",
               std::regex_constants::ECMAScript);
func_arg_regex_ = std::regex(
    "<arg_key>([\\s\\S]*?)</arg_key>(?:\\n|\\s)*<arg_value>([\\s\\S]*?)</"
    "arg_value>",
    std::regex_constants::ECMAScript);
```

**崩溃触发点**: `glm47_detector.cpp` 第 270 行

```cpp
std::sregex_iterator iter(text.begin(), text.end(), func_call_regex_);
```

### 技术原因

1. **正则表达式模式 `[\s\S]*?`**: 该模式用于匹配任意字符（包括换行符），采用非贪婪匹配策略。
2. **libstdc++ 的 std::regex 实现缺陷**: GNU C++ 标准库的 `std::regex` 使用递归回溯算法实现。对于 `[\s\S]*?` 这类模式，算法会为输入字符串中的每个字符创建一个栈帧进行递归调用。
3. **栈空间耗尽**: 当输入文本较长时（本次崩溃的输入为 46,007 字节），递归深度超过线程栈空间限制，导致栈溢出。

### 触发条件

当 GLM-4.7 模型生成包含大量内容的工具调用时（例如 `Write` 工具写入大型文件），`detect_and_parse()` 函数尝试用正则表达式匹配整个输出，触发灾难性回溯（Catastrophic Backtracking）。

---

### 触发 Payload 特征

| 指标 | 值 |
|------|------|
| 输入长度 | 46,007 字节 |
| 栈帧数量 | 168,425 帧 |
| 正则模式 | `<tool_call>[\s\S]*?</tool_call>` |
| 崩溃原因 | libstdc++ regex DFS 栈溢出 |

### Payload 结构

```xml
<tool_call>Write<arg_key>content</arg_key><arg_value># API文档提取与比对服务 需求方案文档

## 1. 项目背景
... (约 46KB 的中文 Markdown 内容) ...
</arg_value><arg_key>file_path</arg_key><arg_value>D:\project\...\Test1.md</arg_value></tool_call>
```

模型尝试调用 `Write` 工具写入一个约 46KB 的 Markdown 文档作为 `content` 参数内容。

---

### 直接影响

1. **服务可用性**: 单个请求可导致整个服务进程崩溃
2. **数据丢失**: 进程崩溃时正在处理的其他请求会丢失
3. **用户体验**: 客户端收到连接中断错误

### 潜在风险

1. **拒绝服务攻击**: 攻击者可构造超长输入触发崩溃
2. **可靠性问题**: 正常业务场景（如代码生成、文档写入）可能触发此问题

---

### 方案一：使用字符串查找替代正则表达式（推荐）

对于固定分隔符 `<tool_call>` 和 `</tool_call>`，使用 `std::string::find()` 进行匹配：

```cpp
// 替代 std::regex
size_t start = text.find("<tool_call>");
size_t end = text.find("</tool_call>");
if (start != std::string::npos && end != std::string::npos) {
    std::string content = text.substr(start + 11, end - start - 11);
    // 处理 content...
}
```

**优点**:

- O(n) 时间复杂度，无递归
- 无栈溢出风险
- 性能更优

### 方案二：使用 RE2 正则表达式库

Google RE2 使用线性时间算法，不会产生灾难性回溯：

```cpp
#include <re2/re2.h>

static RE2 func_call_regex("<tool_call>([\\s\\S]*?)</tool_call>");
```

**优点**:

- 保持正则表达式的灵活性
- 保证 O(n) 时间复杂度

### 方案三：添加输入长度限制（临时方案）

在正则匹配前检查输入长度：

```cpp
const size_t MAX_INPUT_LENGTH = 32768;  // 32KB
if (text.length() > MAX_INPUT_LENGTH) {
    // 降级处理或返回错误
}
```

**注意**: 这只是临时缓解措施，不能从根本上解决问题。

---

## 相关提交历史

| 提交哈希 | 日期 | 描述 | 是否修改正则 |
|----------|------|------|--------------|
| `0c082f3` | 2025-12-21 | 引入 GLM-4.7 detector | ✅ 引入问题代码 |

---

## 参考资料

1. [Catastrophic Backtracking in Regular Expressions](https://www.regular-expressions.info/catastrophic.html)
2. [RE2: A principled approach to regular expression matching](https://github.com/google/re2)
3. [libstdc++ std::regex implementation notes](https://gcc.gnu.org/onlinedocs/libstdc++/manual/strings.html#strings.string.regex)

---

### 完整调用栈（摘要）

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  std::__detail::_Executor<...>::_M_dfs(...) at regex_executor.tcc:...
... (重复 168,423 帧) ...
#168424  std::__detail::_Executor<...>::_M_dfs(...) at regex_executor.tcc:...
#168425  xllm::function_call::Glm47Detector::detect_and_parse(...) at glm47_detector.cpp:270
```

### PR DESCRIPTION
**Pull request by QwertyJack**
## Summary

- Replace `std::regex` with `std::string::find()` and `substr()` in GLM-4.7 detector
- Eliminates stack overflow on large tool call payloads (46KB+)
- O(n) time complexity with no recursion

## Root Cause

The `[\s\S]*?` pattern in libstdc++ `std::regex` uses recursive backtracking, creating one stack frame per character. On inputs >40KB, this exceeds the 8MB stack limit causing SIGSEGV.

## Changes

- `glm47_detector.h`: Remove `#include <regex>` and 3 regex members, add 3 string-based helper declarations
- `glm47_detector.cpp`: Implement `find_tool_call_ranges()`, `parse_tool_call_content()`, `extract_argument_pairs()` using string operations

## Test plan

- [x] Run `glm47_detector_test` (18 test cases)
- [x] Verify 50KB+ payload no longer crashes

Fixes #751

### CODE REVIEW

File: xllm/function_call/glm47_detector.cpp [hunk 1]
```diff
@@ -486,128 +528,117 @@ StreamingParseResult Glm47Detector::parse_streaming_increment(
...
-          }
+        // Update the streamed length
+        streamed_raw_length_ = current_raw_length;
+      }
 
-          try {
-            std::sregex_iterator arg_iter(
-                func_args_raw.begin(), func_args_raw.end(), func_arg_regex_);
-            std::sregex_iterator arg_end;
+      if (is_tool_end_flag) {
```
Comment (XuZhang99) [inline xllm/function_call/glm47_detector.cpp:698]: no other `else` for this if, so maybe we could simplify line these two `if` at line 606 and 607.

File: xllm/function_call/glm47_detector.cpp [hunk 2]
```diff
@@ -70,6 +58,78 @@ bool Glm47Detector::has_tool_call(const std::string& text) {
   return text.find(bot_token_) != std::string::npos;
 }
 
+std::vector<std::pair<size_t, size_t>> Glm47Detector::find_tool_call_ranges(
+    const std::string& text) const {
+  std::vector<std::pair<size_t, size_t>> ranges;
+  ranges.reserve(4);
```
Comment (XuZhang99) [inline xllm/function_call/glm47_detector.cpp:115]: why reserve 4? add comments.

File: xllm/function_call/glm47_detector.cpp [hunk 3]
```diff
@@ -70,6 +58,78 @@ bool Glm47Detector::has_tool_call(const std::string& text) {
...
+    size_t key_start = args_raw.find(key_open, pos);
+    if (key_start == std::string::npos) break;
+    key_start += key_open.length();
+
+    size_t key_end = args_raw.find(key_close, key_start);
+    if (key_end == std::string::npos) break;
+
+    size_t val_start = args_raw.find(val_open, key_end);
+    if (val_start == std::string::npos) break;
+    val_start += val_open.length();
```
[the remark this answers is not in the document]
Comment (QwertyJack) [reply xllm/function_call/glm47_detector.cpp:181]: Good catch! Fixed by adding the intervening key check as suggested.

File: xllm/function_call/glm47_detector.cpp (hunk 2 above)
Comment (QwertyJack) [reply xllm/function_call/glm47_detector.cpp:115]: Added comment explaining the magic number.

File: xllm/function_call/glm47_detector.cpp (hunk 1 above)
Comment (QwertyJack) [reply xllm/function_call/glm47_detector.cpp:698]: This is existing logic from the original code. The two branches handle different cases:
1. `is_first_param_`: No args were streamed yet, output `{}`
2. `else if`: Args exist but need closing brace `}`

Kept as-is to preserve original behavior and make the intent clear.

**Comment by yingxudeng** [comment]
Covered by unit tests and all tests pass. LGTM.
