### PR TITLE
bugfix: allow non-text content in chat JSON for VLM backends.

### LINKED ISSUE #801: [Bug]: client端message type为image_url时报错：Non-text content requires multimodal endpoint
### Your environment

server 命令：
```
MODEL_PATH=/path/to/Qwen2.5-VL-7B-Instruct
MASTER_NODE_ADDR="127.0.0.1:3331"                  
START_PORT=1800                                  
START_DEVICE=0                                    
NNODES=4                                           
DP_SIZE=1

for (( i=0; i<$NNODES; i++ ))
do
  PORT=$((START_PORT + i))
  DEVICE=$((START_DEVICE + i))
  ./build/xllm/core/server/xllm \
    --model $MODEL_PATH \
    --devices="mlu:$DEVICE" \
    --port $PORT \
    --master_node_addr=$MASTER_NODE_ADDR \
    --nnodes=$NNODES \
    --max_memory_utilization=0.8 \
    --max_tokens_per_batch=20480 \
    --max_tokens_per_chunk_for_prefill=2048 \
    -backend vlm \
    --enable_shm \
    --block_size=16 \
    --enable_graph \
    --dp_size=$DP_SIZE \
    --enable_prefix_cache=true \
    --enable_chunked_prefill=true \
    --enable_schedule_overlap=true \
    --node_rank=$i  &
done
```
加载图片命令：
```
import sys
from openai import OpenAI
import base64
import cv2
import time

QUESTION = "What is the content of each image?"

# Modify OpenAI's API key and API base to use 9n-transformer's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://127.0.0.1:1800/v1"
urls = [openai_api_base]
count = 1

import requests
import json

def get_model_id():
    try:
        # 发送 HTTP 请求
        response = requests.get(f"{openai_api_base}/models")
        response.raise_for_status()  # 检查请求是否成功

        # 解析 JSON 数据
        data = response.json()

        # 提取第一个模型的 ID
        model_id = data['data'][0]['id']
        print(f"find model: {model_id}")
        return model_id

    except requests.exceptions.RequestException as e:
        print(f"请求错误: {e}")
        return None
    except (KeyError, IndexError) as e:
        print(f"JSON 解析错误: {e}")
        return None
    except json.JSONDecodeError as e:
        print(f"JSON 解码错误: {e}")
        return None

for openai_api_base in urls:
    print(f"post {openai_api_base}")

    client = OpenAI(
        # defaults to os.environ.get("OPENAI_API_KEY")
        api_key=openai_api_key,
        base_url=openai_api_base,
        max_retries = 0,
        timeout = 60*100,
    )


    # Function to encode the image
    def encode_image(file_path):
        if "jfs" in file_path:
            img = requests.get("http://img10.360buyimg.local/da/" + file_path, timeout=5).content
            encoded_string = base64.b64encode(img)
        else:
            with open(file_path, "rb") as image_file:
                encoded_string = base64.b64encode(image_file.read())
        return encoded_string.decode("utf-8")


    image_path = '/path/to/demo.jpeg'
    im = cv2.imread(image_path)
    print(f"im={type(im)}  image_path={image_path}")
    if im is not None:
        print(f"shape={im.shape}")
    else:
        print(f"path={image_path}")

    # Getting the base64 string
    base64_image = encode_image(image_path)

    text = QUESTION
    message = {
        "role": "user",
        "content": [
             {
                "type": "image_url",
                 "image_url": {
                     "url": f"data:image/jpeg;base64,{base64_image}"
                },
           },
            {
                "type": "text",
                "text": text
            },

        ],
    }


    stream=False
    for idx in range(count):
        st = time.time()
        chat_completion = client.chat.completions.create(
            messages=[message],
            model=get_model_id(),
            stream=stream,
            max_tokens=256,
            temperature=0.0
        )
        print(f" cost is {time.time()-st}")

        print(f"Chat completion results: {chat_completion}")
        if stream:
            for chunk in chat_completion:
                print(chunk)
        else:
            print("-" * 50)
            generated_text = chat_completion.choices[0].message.content
            print(generated_text)
            print("-" * 50)
```

### 🐛 Describe the bug

预处理chat json时在 #740 PreprocessChatJson 中报错
报错信息：
```
E20260126 18:21:56.345738 65919 api_service.cpp:293] Complex message preprocessing failed: Non-text content requires multimodal endpoint
```

### PR DESCRIPTION
**Pull request by QwertyJack**
## Summary

- Fixes #801: VLM backends now correctly accept `image_url` and other non-text content in chat messages
- PR #740 introduced `PreprocessChatJson` which incorrectly rejected all non-text content types
- Root cause: shared template function had no awareness of backend type (LLM vs VLM)

## Changes

- Add `is_multimodal` parameter to `PreprocessChatJson` and `ChatCompletionsImpl`
- VLM backend (`-backend vlm`): passes non-text content through unchanged for downstream processing
- LLM/REC backends: returns helpful error message with guidance to use `-backend vlm`
- Extract function to `chat_json_utils.h` for testability
- Add 18 test cases covering text-only, multimodal, and error scenarios
- Fix build: add missing library dependencies (`c_sec`, `nnopbase`)

## Related Issues

- During testing of this PR, discovered #884 (mRoPE position tensor shape mismatch in NPU graph mode), fixed in #885

## Test plan

- [x] Run `api_service_test` to verify all 18 new test cases pass
- [x] Test VLM backend with `image_url` content (reproducer from issue #801)
- [x] Test LLM backend with text-only array content (should still combine into string)
- [x] Test LLM backend with `image_url` content (should return helpful error)

### CODE REVIEW

File: xllm/api_service/api_service.cpp [hunk 1]
```diff
@@ -208,20 +214,37 @@ std::pair<Status, std::string> PreprocessChatJson(std::string json_str) {
...
             return {Status(StatusCode::INVALID_ARGUMENT,
-                           "Non-text content requires multimodal endpoint"),
+                           "Non-text content (e.g., image_url) requires "
+                           "multimodal backend (-backend vlm)"),
                     ""};
           }
+          // Multimodal endpoint: leave array unchanged for downstream
+          // processing
+          continue;
+        }
```
[the remark this answers is not in the document]
Comment (QwertyJack) [reply xllm/api_service/api_service.cpp:244]: Thanks for catching this! Both issues are valid:

1. **Validation Bypass**: Fixed. Now we iterate through ALL items without breaking early, validating text items have proper `text` field even when non-text content is present.

2. **Type Mismatch DoS**: Fixed. For multimodal backends, we now preserve the array structure for ALL content arrays (including text-only), since `MMChatMessage.content` is `repeated MMInputData` in protobuf.

Key changes:
- Removed early `break` - now validates all items in the loop
- Added `is_multimodal || has_non_text` check to preserve arrays for VLM
- Added test case `MalformedTextInMultimodalContent` to verify validation works

File: xllm/api_service/api_service.cpp [hunk 2]
```diff
@@ -287,7 +306,7 @@ void ChatCompletionsImpl(std::unique_ptr<Service>& service,
   ctrl->request_attachment().copy_to(&attachment, content_len, 0);
 
   auto [preprocess_status, processed_json] =
-      PreprocessChatJson(std::move(attachment));
+      PreprocessChatJson(std::move(attachment), is_multimodal);
```
[the remark this answers is not in the document]
Comment (QwertyJack) [reply xllm/api_service/api_service.cpp]: This is a **false positive**. The `butil::IOBuf::copy_to(std::string*, size_t, size_t)` overload exists in brpc and is the standard API for copying IOBuf contents to a string. It correctly resizes the string and copies data into it.

This exact pattern is used elsewhere in this codebase (see `call.cpp:60`) and is an established, working pattern in brpc applications.

The signature is:
```cpp
size_t copy_to(std::string* s, size_t n = (size_t)-1L, size_t pos = 0) const;
```

This safely appends `n` bytes from position `pos` to the string `s`, not to a raw buffer at the address of the string object.

File: xllm/api_service/api_service.cpp [hunk 3]
```diff
@@ -329,16 +348,28 @@ void APIService::ChatCompletionsHttp(
...
     CHECK(chat_service_impl_) << " chat service is invalid.";
-    ChatCompletionsImpl<ChatCall, ChatServiceImpl>(
-        chat_service_impl_, done_guard, ctrl, request, response);
+    ChatCompletionsImpl<ChatCall, ChatServiceImpl>(chat_service_impl_,
+                                                   done_guard,
+                                                   ctrl,
+                                                   request,
+                                                   response,
+                                                   /*is_multimodal=*/false);
   }
```
[the remark this answers is not in the document]
Comment (QwertyJack) [reply xllm/api_service/api_service.cpp:378]: This is **pre-existing code** that wasn't introduced by this PR. The only change here is adding the `is_multimodal` parameter to the existing function calls.

Refactoring the branch structure to combine `llm` and `rec` is out of scope for this bug fix PR. While it's a valid style improvement, making unrelated changes would:
1. Increase the diff size and review burden
2. Risk introducing regressions unrelated to issue #801
3. Violate the principle of minimal changes for bug fixes

This could be addressed in a separate refactoring PR if desired.

**Comment by wly-115** [comment]
i understand that for multimodal scenarios, the request data doesn't need to be modified at all. can we avoid deserializing it into JSON in multimodal cases?

**Comment by QwertyJack** [comment]
@wly-115 Good suggestion! Implemented in the latest commit.

For multimodal backends, `PreprocessChatJson` now returns early without parsing:

```cpp
if (is_multimodal) {
  return {Status(), std::move(json_str)};
}
```

This avoids the JSON deserialization overhead entirely for VLM requests. Validation for malformed content will happen downstream in the VLM handler.

**Comment by wly-115** [comment]
The VLM backend doesn't yet support prefix cache, chunk prefill, or graph execution (in progress: https://github.com/jd-opensource/xllm/pull/637). Please disable the corresponding gflags in start_vlm_server.sh.

**Comment by QwertyJack** [comment]
@wly-115 Good catch - the e2e folder was accidentally included. It's been removed from the PR. Those scripts are for local testing only.

File: xllm/api_service/api_service.cpp [hunk 4]
```diff
@@ -191,9 +192,19 @@ size_t GetJsonContentLength(const brpc::Controller* ctrl) {
...
 }
 
+}  // namespace
+
 // Preprocess chat JSON to normalize array content to string.
+// For text-only backends, combines text array items into a single string.
+// For multimodal backends, passes through unchanged without parsing.
 // Returns Status with processed JSON on success, or error status on failure.
-std::pair<Status, std::string> PreprocessChatJson(std::string json_str) {
+std::pair<Status, std::string> PreprocessChatJson(std::string json_str,
```
Comment (yq33victor) [inline xllm/api_service/api_service.cpp]: why move the funtion out of `namesapce{}`. This function is not used anywhere else.

Comment (yq33victor) [inline xllm/api_service/api_service.cpp]: rename it to `preprocess_chat_json`

File: xllm/api_service/api_service.cpp [hunk 5]
```diff
@@ -329,16 +345,28 @@ void APIService::ChatCompletionsHttp(
 
   if (FLAGS_backend == "llm") {
     CHECK(chat_service_impl_) << " chat service is invalid.";
-    ChatCompletionsImpl<ChatCall, ChatServiceImpl>(
-        chat_service_impl_, done_guard, ctrl, request, response);
+    ChatCompletionsImpl<ChatCall, ChatServiceImpl>(chat_service_impl_,
```
Comment (yq33victor) [inline xllm/api_service/api_service.cpp]: rename `ChatCompletionsImpl`

File: xllm/api_service/api_service.cpp (hunk 4 above)
Comment (QwertyJack) [reply xllm/api_service/api_service.cpp]: Moved out of anonymous namespace for unit testing - the function is tested in `chat_json_utils_test.cpp`.

Comment (QwertyJack) [reply xllm/api_service/api_service.cpp]: Done. Renamed to `preprocess_chat_json` to follow the codebase snake_case convention for free functions.

File: xllm/api_service/api_service.cpp (hunk 5 above)
Comment (QwertyJack) [reply xllm/api_service/api_service.cpp]: Done. Renamed to `chat_completions_impl` to match the codebase convention.
